apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sonarqube-oidc
  namespace: sonarqube
spec:
  vaultAuthRef: my-vault-connection
  mount: secret
  path: sonarqube/oidc
  type: kv-v2
  destination:
    create: true
    name: sonarqube-oidc
