---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-monitoring
  namespace: default
spec:
  encryptedData:
    passcode: AgCnHblE7/pAxRIku6tNY2ughGvkODBA4pOwpKRBLKiECg3614rWoaZDvozXjTcHQToxbAywWbgKuZiOvpgQCkn6haBCMtGW+Oun22ObHsRBa2w+iOyaelSU3+nAZP852JUgvwuXzyoECPYqbeMH7brs5AthpZQr911UktcwekI6VQKwLtpddk+9RRfj6Nxahg/bpOxFfsD/dLx6ebx0lBII9YNHqz8TFuFFyV96kwUptwZd8WHQTw6NRP8aUDKxQAx6/17XBpXkWQOsjICxYXiQ2TjQsEBqnu22Ba9GY5BwQpu3YGY5CZHLF3+4cswG6me394HGbLeedPAzS/EYJSGMQWaefD35DQTqZ2lGOWG1fFi+CmFyoR02zm+2DRbZFEgusKi1f03y46/66ST1t0iJN+HDWHyrOiCnSwB5qLcGRt3Sz4MgcJ6TU6EAWP1tfzSRF2ntHr1/l4NbIsOD1SFMen/vUGLXW3etQanjcf55VdXwMMb+ylF2rEPp+XV671o1xpBRdqVwVLdIjLHLyZ0iDINHRJ1Se7B00pHoC9xzUJh3NIxjNw1doCg3DbV/dN1d5hQ/pvt/+FPSKSM6lU5qsv2TpYWuD+3P0eyL+dtyfLLQ2EGfXdYb4eA8QoB5O8BgW9pzFq84Ch7WojQVYFKmte/oXdbUqWLKeUb5ClID4yekwENZzoubFRIBAmICa6klMAZmFrhM7fKjk3+IMQ==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-monitoring
      namespace: default
