---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-monitoring
  namespace: sonarqube
spec:
  encryptedData:
    passcode: AgAcZF0RPGKmlkugZrI1NzRfGwue8mYiV3+N7QFwpRycAmsHQ1e1bYA5d3YmnAEuqgIEBeSzCeuwvENdjr+EttgMfrbTWCuw/JFKJuiF/2BPLo1Xru7qZuNjbOxqRZwFvH6U2Q0WRiNTNUMAmNjAPp0SxwNaIiGdJ1h9ODhUTI14o1TkmB8xQNe5z321Pxa8XvLMnCf0x3G32C+Sxu1xiV0rx8Y3PWfoDw5PSa/Le2W7L4hrFs+9o1nW1LR6T7oOLrBaLt9GK7k1G8ichGtvgLGZiNxjkkSbnM0kLBzegbdwudV5Y5LTyPanAlqhGz7pj914yEaXm5gywuhE3yA7RMP+4IMggKzXpjF3a7/fw4TU3ZyKhjPM4PijTGtEpsL0EqpgsmUibLdE5ahku3CEnilgo7zqqZ/tAiYDB4cBTqlAaExzBGjaDibxXFKMeHy2AoEtoamXw/htbLh94VUFW65qW0hC2C1qYxveglVtSUC+6ygyPk4QT4nbwQcWly+gGJx2qe22AQj1AsEQuUh1s0KY9dYNF9I3Th3xyL/+smOtmen74h1YneQESZkqTPZwFMmeNGxgrYSjplc2e4+BXEcjilfw71+MjDEfBpogwznRBLoBTFidRtB8p3MFo5XrmhA8Bdt6Dr9BgNymERD2kR//Gwpv5sn5EVtKLzNB/51MOH2nikG5c+shDevgXIeFFqRnJ3qG4rU53O6S0R+wRA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-monitoring
      namespace: sonarqube
