apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sonarqube-monitoring
  namespace: sonarqube
spec:
  vaultAuthRef: my-vault-connection
  mount: kv
  path: secret/sonarqube/monitoring
  type: kv-v2
  destination:
    create: true
    name: sonarqube-monitoring
