---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-monitoring
  namespace: sonarqube
spec:
  encryptedData:
    passcode: AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-monitoring
      namespace: sonarqube
