apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: my-vault-connection
  namespace: sonarqube
spec:
  vaultConnectionRef: my-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: demo
    serviceAccount: default
