apiVersion: apps/v1
kind: Deployment
metadata:
  name: hidmo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hidmo-web
  template:
    metadata:
      labels:
        app: hidmo-web
    spec:
      initContainers:
        - name: generate-env
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              apk add --no-cache gettext >/dev/null
              cat <<'EOF' > /env/env.js.template
              window._env_ = {
                VITE_API_URL: "$VITE_API_URL",
                VITE_RELEASE_API_URL: "$VITE_RELEASE_API_URL",
                VITE_KEYCLOAK_URL: "$VITE_KEYCLOAK_URL",
                VITE_KEYCLOAK_REALM: "$VITE_KEYCLOAK_REALM",
                VITE_KEYCLOAK_CLIENT_ID: "$VITE_KEYCLOAK_CLIENT_ID",
                VITE_GITHUB_CLIENT_ID: "$VITE_GITHUB_CLIENT_ID",
                VITE_GITHUB_CLIENT_SECRET: "$VITE_GITHUB_CLIENT_SECRET"
              };
              EOF
              envsubst < /env/env.js.template > /env/env.js
          env:
            - name: VITE_API_URL
              value: "https://api-hidmo.leultewolde.com/kitchen/stored-items"
            - name: VITE_RELEASE_API_URL
              value: "https://api-hidmo.leultewolde.com/kitchen/release-management"
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_URL
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_REALM
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_CLIENT_ID
            - name: VITE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_GITHUB_CLIENT_ID
            - name: VITE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_GITHUB_CLIENT_SECRET
          volumeMounts:
            - name: env-js
              mountPath: /env
      containers:
        - name: hidmo-web
          image: ivtheforth/hidmo-web:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "https://api-hidmo.leultewolde.com/kitchen/stored-items"
            - name: VITE_RELEASE_API_URL
              value: "https://api-hidmo.leultewolde.com/release-management"
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_URL
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_REALM
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_KEYCLOAK_CLIENT_ID
            - name: VITE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_GITHUB_CLIENT_ID
            - name: VITE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_GITHUB_CLIENT_SECRET
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1024Mi"
          volumeMounts:
            - name: env-js
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
      volumes:
        - name: env-js
          emptyDir: {}
