apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hidmo-vault-token
spec:
  vaultAuthRef: hidmo-vault-connection
  mount: secret
  path: hidmo/frontend/prod
  type: kv-v2
  destination:
    create: true
    name: frontend-secrets
