apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-service
  template:
    metadata:
      labels:
        app: external-service
    spec:
      containers:
        - name: external-service
          image: docker.io/ivtheforth/external-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EXTERNAL_API_BASE_URL
              value: "https://world.openfoodfacts.org"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: VAULT_TOKEN
                  key: VAULT_TOKEN
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
