apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-service-scaledobject
spec:
  scaleTargetRef:
    name: external-service
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
