apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
        - name: micro1
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
