apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-credentials
  namespace: postgres-systemtest
spec:
  vaultAuthRef: my-vault-connection
  mount: secrets
  path: secret/postgres-systemtest/postgres-credentials
  type: kv-v2
  destination:
    create: true
    name: postgres-credentials
