apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: my-vault-connection
  namespace: postgres-systemtest
spec:
  address: https://vault.leultewolde.com
  skipTLSVerify: false
