apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  vaultAuthRef: my-vault-connection
  mount: secret
  path: argocd/oidc
  type: kv-v2
  destination:
    create: true
    name: argocd-secret
    overwrite: true
