apiVersion: apps/v1
kind: Deployment
metadata:
  name: km-ingredients-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: km-ingredients-service
  template:
    metadata:
      labels:
        app: km-ingredients-service
    spec:
      containers:
        - name: km-ingredients-service
          image: docker.io/ivtheforth/km-ingredients-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: VAULT_TOKEN
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: new-relic-license-key
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-password
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-url
            - name: MINIO_ACCESS_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-access-name
            - name: MINIO_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-access-secret
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-bucket
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
