resources:
- deployment.yaml
- service.yaml
- db-job.yaml
# - scaledobject.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ingredients-create-db
  files:
  - sql/create-db.sql
