resources:
- deployment.yaml
- service.yaml
- db-job.yaml
- migrate-job.yaml
- secret.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ingredients-migrations
  files:
  - sql/V1__init.sql
- name: ingredients-create-db
  files:
  - sql/create-db.sql
images:
- name: docker.io/ivtheforth/km-ingredients-service
  newTag: 5bfa8b5f549593964b2d4dcd6ce368ced49a7cea
