resources:
- deployment.yaml
- service.yaml
- db-job.yaml
- migrate-job.yaml
- secret.yaml
# - kaniko-job.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ingredients-migrations
  files:
  - sql/V1__init.sql
- name: ingredients-create-db
  files:
  - sql/create-db.sql
images:
- name: docker.io/ivtheforth/km-ingredients-service
  newTag: f7756649c7cc2b0e64ea32e043aeca1b108f0239
