apiVersion: batch/v1
kind: Job
metadata:
  name: ingredientsDB-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: flyway
          image: flyway/flyway:9
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/ingredientsDB
            - name: FLYWAY_USER
              value: postgres
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
          volumeMounts:
            - name: migrations
              mountPath: /flyway/sql
          command: ["flyway"]
          args: ["migrate"]
      volumes:
        - name: migrations
          configMap:
            name: ingredientsDB-migrations
