apiVersion: batch/v1
kind: Job
metadata:
  name: ingredients-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: flyway
          image: flyway/flyway:11.10.1 # ✅ Upgrade Flyway version
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/ingredients_db
            - name: FLYWAY_USER
              value: postgres
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
          volumeMounts:
            - name: migrations
              mountPath: /flyway/sql
          command: ["flyway"]
          args: ["repair"] # ✅ Change to ["repair"] if you want to repair first
      volumes:
        - name: migrations
          configMap:
            name: ingredients-migrations
