apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: km-ingredients-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: km-ingredients-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
