---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgAFZVRDv1eXcYSoF8QZrlmEkiWVuGEu2XUXrlgdN8ttiGQLwrO8bM+Gq9K6Ov03Xc26LcQPd5oMpLiRCIstNV12lVeaY143VJj+rpHbryAIP48f9hDqKI2Evotnn57MkGitzxYAPDdOUb+kGqgBO8B+W/FrYEg6kPUJJ3t7CZBQRiDYY+sATKgCUkb8aUOA1DybevtVHeLT3r3c4V203g6PpP5xpAgwWsn/Q0IYls9VnngukO0h8yqZa+jxyqfetAEqlKbXSWRe53tkvOFIlKMdHwa9tJ8WRakyymOicBLM5MLS6Dia7TKqroP6NqtQcqVma8v/jvJWSKa6SoXRpvoIaBDqEaxp7XcHVQPLg4rS/b+rub1M16JgmzrDOfWI3XUGmN1w9uiJOnhoDSCBwr5BPL4wzcp8wfD11AVF60m+4yZVin+dnMsgc6NknNSHAiifzdPzf8RfiqpFr94sefGZRS2tXB4RzY5uPk1uZycV2y6OvCUNN7wyh3575kpBGiTel4zIhoZMsKGPJBjmVc6IausTPQUpU7k70ft026hab1vipLntyzFHHKJCPhYaz+/diDGUI6pAd+Eh8tMLhKd66n/4BQLPYfwXL0J6yVXUHoMCoVIZvitIU3w98bPxItu+aJTGMgBiacpMbW6hTEMStQmlhwEE4DqLefofcE1z/8vzw0fU+blcxFCvyB/pjfOtt+TPlIWdnvFxqw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: postgres
