apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgA/pccVrVugNUtSupuCuWLOVyVAvx4zYkuQgVQqxM6BdfUdZAWdTM/MB0Xx8qyenGv2iKDMGU7VXRn/2PzM0/m6jmkPvfVCcle0XJZ18rbKdnKtm3NYzgEHpnxZ22UEJMj5o3azD4T1EUXTsefW822YLNTompAzDJnXFoAW44BLd0pfL0ATutxSsxv+y60VmeS7gprYiAAfSPjLPlc6tjknjFtjtjPc1RjPkhPt/WNHEp9sAR3nwsQXvj9cy9vCU7zBvOW9PJ1eGIzSRE49lKZUGB6tqivPuZrxStILnHZpwQp+p1iTOXV3cb9pOcY+q1iYa99pS9Dnpe9JIFvJG94GEqdm0c5EBKdWKUL9WneVU458S8qT/ROGrwP2nabkk9/plPdEW9NuVifzWcDjkP2iyYYCFVgKey1G9WzoE/160wUJ7rEtnLZqgXeSuCAKDFol4KECCCUtkV9t0pMEKwY0M/sXNA9Jr9nYyT2x+ix3MRtb+FUDFVRbx2dN6Pbw4R0h8V7r7IpqeR/PRt1ZA6Gq9pBmyFnL7ve8JjOTCWFb62rLFNf/RPBe4gxauOelZ0LXxb2My2bv+u533EfmXJs2TSsq7V3ulnu+JkUu9inMAy5jnXd3SEPsz7wVNIKT+kT26KKBiqaMCy7GSqbNnLwMCmfvvTr5NAULkU9gccaEcriNavWJJ0zG6dHoXzaIP2xxHCqVEA9b3FWfUw==
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
    type: Opaque
