apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.111.11
    helm:
      values: |
        artifactory:
          service:
            type: LoadBalancer
            annotations:
              external-dns.alpha.kubernetes.io/hostname: artifactory.leultewolde.com
        ingress:
          enabled: true
          hosts:
            - artifactory.leultewolde.com
          annotations:
            external-dns.alpha.kubernetes.io/hostname: artifactory.leultewolde.com
      releaseName: artifactory
  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
