apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leultewolde/hidmo-argo-gitops.git
    targetRevision: HEAD
    path: manifests/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true         # Delete resources not in Git anymore
      selfHeal: true      # Re-apply if someone changes the resource manually
    syncOptions:
      - CreateNamespace=true
