apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hidmo-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leultewolde/hidmo-argo-gitops.git
    targetRevision: HEAD
    path: manifests/hidmo/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: hidmo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
