apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hidmo-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leultewolde/hidmo-argo-gitops.git
    targetRevision: HEAD
    path: manifests/hidmo-web/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hidmo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
