apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: km-ingredients-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: km-ingredients-service=docker.io/ivtheforth/km-ingredients-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/km-ingredients-service.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/leultewolde/hidmo-argo-gitops.git
    targetRevision: HEAD
    path: manifests/hidmo/microservices/ingredients-service
  destination:
    server: https://kubernetes.default.svc
    namespace: hidmo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
