apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 17.0.8
    helm:
      values: |
        image:
          tag: 2025.6.13-debian-12-r0

        auth:
          rootUser: minioadmin
          rootPassword: minioadmin

        defaultBuckets: "mybucket"

        mode: standalone

        persistence:
          enabled: true
          size: 10Gi
          storageClass: local-path

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        service:
          type: ClusterIP

        console:
          enabled: true
          image:
            tag: 2.0.2-debian-12-r0
          service:
            type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: minio.leultewolde.com
          path: /
          pathType: Prefix
        console:
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: console-minio.leultewolde.com
            path: /
            pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

