---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://oteemo.github.io/charts
    chart: sonatype-nexus
    targetRevision: 5.5.0
    helm:
      values: |
        nexus:
          service:
            type: NodePort
            annotations:
              external-dns.alpha.kubernetes.io/hostname: nexus.leultewolde.com
        nexusProxy:
          env:
            nexusHttpHost: nexus.leultewolde.com
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: nexus.leultewolde.com
          path: /
          pathType: Prefix
          tls:
            enabled: false
      releaseName: nexus
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
