---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sonatype/nxrm3-ha-repository
    path: nxrm-ha
    targetRevision: 82.0.0
    helm:
      values: |
        ingress:
          enabled: true
          host: nexus.leultewolde.com
          hostPath: /
          defaultRule: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: nexus.leultewolde.com
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: nexus.leultewolde.com
          nexus:
            enabled: true
            type: NodePort
        statefulset:
          replicaCount: 1
        container:
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      releaseName: nexus
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
