apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-systemtest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.6
    helm:
      values: |
        auth:
          username: postgres
          database: appdb
          existingSecret: postgres-credentials
        primary:
          persistence:
            size: 1Gi
            storageClass: local-path
          service:
            type: LoadBalancer
            annotations:
              external-dns.alpha.kubernetes.io/hostname: postgres-systemtest.leultewolde.com
      releaseName: postgres-systemtest
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-systemtest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
