apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leultewolde/hidmo-argo-gitops.git
    targetRevision: HEAD
    path: manifests/postgres
    kustomize:
      # explicitly run kustomize with Helm support enabled
      buildOptions: --enable-helm
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
