apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 2025.3.1
    helm:
      values: |
        community:
          enabled: true
        persistence:
          enabled: true
          storageClass: local-path
          size: 5Gi
        service:
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: sonar.leultewolde.com
        postgresql:
          enabled: true
          persistence:
            enabled: true
            storageClass: local-path
            size: 5Gi
        monitoringPasscodeSecretName: sonarqube-monitoring
        monitoringPasscodeSecretKey: passcode
        sonarProperties:
          sonar.auth.oidc.enabled: "true"
          sonar.auth.oidc.issuerUri: https://auth.leultewolde.com/realms/hidmo
          sonar.auth.oidc.clientId: sonarqube-client
        env:
          - name: SONAR_AUTH_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sonarqube-oidc
                key: client-secret
      releaseName: sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
