apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 2025.4.2
    helm:
      values: |
        community:
          enabled: true
        persistence:
          enabled: true
          storageClass: local-path
          size: 5Gi
        plugins:
          install:
            - https://github.com/sonar-auth-oidc/sonar-auth-oidc/releases/download/v3.0.0/sonar-auth-oidc-plugin-3.0.0.jar
        service:
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: sonar.leultewolde.com
        postgresql:
          enabled: true
          persistence:
            enabled: true
            storageClass: local-path
            size: 5Gi
        monitoringPasscodeSecretName: sonarqube-monitoring
        monitoringPasscodeSecretKey: passcode
        sonarProperties:
          sonar.core.serverBaseURL: https://sonar.leultewolde.com
          sonar.auth.oidc.enabled: "true"
          sonar.auth.oidc.issuerUri: https://auth.leultewolde.com/realms/hidmo
          sonar.auth.oidc.clientId: sonarqube-client
          sonar.forceAuthentication: "true"
        env:
          - name: SONAR_AUTH_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sonarqube-oidc
                key: client-secret
      releaseName: sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
