apiVersion: batch/v1
kind: Job
metadata:
  name: ingredients-create-db
spec:
  template:
    spec:
      containers:
        - name: create-db
          args:
            - "-h"
            - "postgres-postgresql.postgres-staging.svc.cluster.local"
            - "-U"
            - "postgres"
            - "-f"
            - "/scripts/create-db.sql"
