apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: my-vault-connection
  namespace: postgres-staging
spec:
  vaultConnectionRef: my-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: hidmo-app
    serviceAccount: default
