apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
        - name: micro2
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=hello from micro2"
            - "-listen=:5678"
          ports:
            - containerPort: 5678
