apiVersion: apps/v1
kind: Deployment
metadata:
  name: hidmo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hidmo-backend
  template:
    metadata:
      labels:
        app: hidmo-backend
    spec:
      containers:
        - name: kong
          image: kong:3.9.1
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /etc/kong/kong.yml
            # Limit admin API to localhost so it is not reachable from other pods
            - name: KONG_ADMIN_LISTEN
              value: "127.0.0.1:8001"
            - name: KONG_STATUS_LISTEN
              value: "0.0.0.0:8100"
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong
          ports:
            - containerPort: 8000
            - containerPort: 8443
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
