apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  labels:
    app: hidmo-backend
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: micro1
        url: http://micro1
        routes:
          - name: micro1
            paths:
              - /micro1
      - name: km-ingredients-service
        url: http://km-ingredients-service:8001
        routes:
          - name: km-ingredients-service
            paths:
              - /kitchen/stored-items
            strip_path: true
      - name: external-service
        url: http://external-service:8080
        routes:
          - name: external-service
            paths:
              - /external
            strip_path: true
