resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - kong-config.yaml
  - microservices/micro1
  # - microservices/micro2
  - microservices/ingredients-service
  - microservices/external-service
  - vault-token.yaml
  - postgres-credentials.yaml
  - vault-connection.yaml
  - vault-auth.yaml
