apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-credentials
spec:
  vaultAuthRef: my-vault-connection
  mount: kv
  path: secret/hidmo/postgres-credentials
  type: Opaque
  destination:
    create: true
    name: postgres-credentials
