apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-token
spec:
  vaultAuthRef: my-vault-connection
  mount: secret
  path: hidmo/vault-token
  type: kv-v2
  destination:
    create: true
    name: vault-token
