apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-token
spec:
  vaultAuthRef: my-vault-connection
  mount: secret
  path: hidmo/kitchen/backend/prod
  type: kv-v2
  destination:
    create: true
    name: backend-secrets
