apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-token
spec:
  vaultAuthRef: my-vault-connection
  mount: kv
  path: secret/hidmo/vault-token
  type: Opaque
  destination:
    create: true
    name: vault-token
