namespace: hidmo-systemtest
resources:
  - ../../hidmo/backend
patchesStrategicMerge:
  - patches/vault-token-namespace.yaml
  - patches/dbhost/micro1-db.yaml
  - patches/dbhost/micro1-migrate.yaml
  - patches/dbhost/micro2-db.yaml
  - patches/dbhost/micro2-migrate.yaml
  - patches/dbhost/ingredients-db.yaml

