namespace: hidmo-systemtest
resources:
  - ../../hidmo/backend
patchesStrategicMerge:
  - patches/dbhost/micro1-db.yaml
  # - patches/dbhost/micro1-migrate.yaml
  - patches/dbhost/ingredients-db.yaml
  - patches/ingress-host.yaml
  - patches/external-service-spring-profile.yaml
  - patches/ingredients-service-spring-profile.yaml
  - patches/vault-token-path.yaml

