apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-service
spec:
  template:
    spec:
      containers:
      - name: external-service
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
