---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgAV9T/o2rDMIcbkUuTig9bOaZwX+AYfotOXrTZttsXwFVJ8xPKPlI8Jux2CIBKLwkhl22OBUsZ9yaOQjh9XhGHAqc+AgvykQI9kGc2hZk8e+dYTShASQxmvT6NDRt7w5eXOORPfOkgnEyq6y8A1ZlnxagnND6f07Amf8xYXBLOevzZNDOY+QEkEAUa4Q685x3MGwwBni/d6QTaFJoMJEkDEuveb+EWT1NuPXQf0DXB2uUNAIVzL7z3Wu/WgJIJ7xgtttOAkYWv0h9k+NGqHfR+HZRbL4rlEX70d0ST33NcB+G6YzgydN/r+FBmbLBJMXbjg4nWTFqg0Ra9z1i0U32EgjUMpc8UVjNL8Ay1GRunGCyT1rhwsuqVKzHrS/jGAuao0q5kg8iNwGAdGH9/nZgGL99agQycMvH6L1DtcHBHMO3xYy1pihYEtKGGBMcZe7EeZE6oMpyeM6nUajftZlBDe6WBdpN7O5YJDb2E2g2AS7jrB8IYbTiBLUX+LFXZqXFZdZBaLfV2KKj0z9f8rL+p1fQv4JnFTLwV8wiBlx7xKuKjsaq03stWWcExUFrX35IZ6YbY6OZ8K3pr10UL5t+YhoPa0IOokxyjq93vE7Fay7AwSjS2qyxxIsz7taa0RUe6ttKNGCY9oogK433nwyZzmVWUBG1qKWb8X+0NTu+7ApL27OK0FkxP400VyTnuuIFK6853NS/++U7eTPg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: postgres
