apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  vaultAuthRef: my-vault-connection
  mount: secret
  path: postgres/postgres-credentials
  type: kv-v2
  destination:
    create: true
    name: postgres-credentials
