---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBIltZRIPBwGV87vrsKUtk+PAOZkO970HRq18vshcgA/txbgKgldfolmVZvjKNQa3E5ZNkjYlz3dVaUf6Q1RI1284KouaLwWuyCRl6lCAAiMarCuk9GHrZXlgArxAMKaxt6RPXwvmzUwFoYwQUg3hcROmrGX71doPDAMUAJnRTJvXbPHXwbukqB+a5T4mZgH+6BssGaGMfwNlYv+C0fNu0iRrffaqldgjfmZdO+NUfRAyHAJEk+sXAOaf5NzgJ8w2eble2MDDHbkjUZTplc4LsqP63O/4RJKbJiEOipI7NoWaM8Lgn+gPcwBFh6Oepsd7ZNFq4IGeFbSy+cJoZchlYYxPCVOzuFoG4NSWxLLikAKkLcPcOZt9CCMP5AoPpC4NTzb4fV6MXB6Fee6ZWgQrNLg7kYz6z8dFb8rR0lpVnGu4kd6Yph9Vwe4s4N6q8R397inr5uB3Wr8JRIMhCjrcVNj91l7ZM0abprmo2eUuvR07duwdZGo3xvxYPsbCOB2JEqTPSMHryqk1IqSVLyghwg2BVGHKwvxaPOjuYnpRk4zHcV44c7CFBFGWn9teLFLhfLDrNjFhJembKeGwvHj4rbHxFP5iCGI3par8y5JAYzbodtbTYFOwnEOZzsTvF11VLxflx1Rnl6rT7suElqgaaqK1iyNydn+tz/RMiK/PpjhGxv12M4/F/ORwHsdE/h+QBo2kv9rhQwskb6HA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: postgres